Create an algorithm that generates an NxN matrix filled with the numbers in a specific pattern
starting from the center. This matrix should follow the pattern illustrated in the attached image.
Input: An integer N representing the size of the square matrix (NxN).
Output: A NxN matrix filled with numbers starting from 1 at the center and moving outward in
a clockwise manner increasing sequentially, filling the matrix completely.
Example:
For N = 5, the output should look like:
1. 21 22 23 24 25
2. 20 7 8 9 10
3. 19 6 1 2 11
4. 18 5 4 3 12
5. 17 16 15 14 13

In [31]:
import numpy as np

In [32]:
import numpy as np

def generate_spiral_matrix(N):
    # Initialize an NxN matrix filled with zeros
    matrix = np.zeros((N, N), dtype=int)
    
    # Start at the center of the matrix
    x, y = N // 2, N // 2
    num = 1  # The first number to place in the matrix

    # Define movement directions: right, down, left, up
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    dir_idx = 0  # Index to track the current direction

    # Place the first number in the center
    matrix[x, y] = num
    num += 1

    # Spiral outward from the center
    for step in range(1, N):  # Incrementally increase the step size
        for _ in range(2):  # Repeat twice for horizontal and vertical moves
            for _ in range(step):
                # Move in the current direction
                x, y = x + directions[dir_idx][0], y + directions[dir_idx][1]
                
                # Check if the position is within bounds
                if 0 <= x < N and 0 <= y < N:
                    matrix[x, y] = num  # Place the current number
                    num += 1
            dir_idx = (dir_idx + 1) % 4  # Change direction clockwise

    # Final pass to complete the outermost layer
    for _ in range(N - 1):
        x, y = x + directions[dir_idx][0], y + directions[dir_idx][1]
        if 0 <= x < N and 0 <= y < N:
            matrix[x, y] = num
            num += 1

    return matrix

Part 2:
Calculate and print the sum of the numbers along both diagonals of the result matrix (primary
and secondary).
Input: Result matrix from the first part.
Output: Sums of the diagonals separately.

In [33]:
# Example usage
N = 5
spiral_matrix = generate_spiral_matrix(N)
print("Spiral Matrix:")
print(spiral_matrix)

Spiral Matrix:
[[21 22 23 24 25]
 [20  7  8  9 10]
 [19  6  1  2 11]
 [18  5  4  3 12]
 [17 16 15 14 13]]


In [34]:
def calculate_diagonal_sums(matrix):
    N = matrix.shape[0]  # Get the size of the matrix
    primary_diagonal_sum = 0  # Sum of the primary diagonal (top-left to bottom-right)
    secondary_diagonal_sum = 0  # Sum of the secondary diagonal (top-right to bottom-left)

    for i in range(N):
        primary_diagonal_sum += matrix[i, i]  # Add elements from the primary diagonal
        secondary_diagonal_sum += matrix[i, N - 1 - i]  # Add elements from the secondary diagonal

    return primary_diagonal_sum, secondary_diagonal_sum

In [35]:
primary_sum, secondary_sum = calculate_diagonal_sums(spiral_matrix)
print(f"Primary Diagonal Sum (top-left to bottom-right): {primary_sum}")
print(f"Secondary Diagonal Sum (top-right to bottom-left): {secondary_sum}")

Primary Diagonal Sum (top-left to bottom-right): 45
Secondary Diagonal Sum (top-right to bottom-left): 57
